substitutions:
  sub_devicename: inkplate
  sub_friendly_name: Inkplate
  sub_glyphs: " \/!'\"%&?=()+,-.:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz°$"
  # Things go faster with a static IP.
  # Comment out manual_ip section under wifi if not using one
  sub_static_ip_address: '192.168.1.214'
  sub_gateway_address: '192.168.1.1'
  sub_subnet_address: '255.255.255.0'

# ================================================================================
#  Logging
# ================================================================================

logger:
  level: DEBUG

# ================================================================================
#  Network & Connectivity
# ================================================================================

# You should be using a secrets.yaml file, either local to your esphome dir
# or pointing to your main HA root file
#
# More info here: https://esphome.io/guides/faq.html

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  output_power: 20.5db
  # This assumes static IP assigned via your router's routing table
  # Comment this out if using Dynamic
  manual_ip:
    static_ip: ${sub_static_ip_address}
    gateway: ${sub_gateway_address}
    subnet: ${sub_subnet_address}
  # Uncomment this if you wish to run as AP
  # ap:
  #   ssid: $sub_devicename
  #   password: !secret ap_password

captive_portal:

ota:
  password: !secret ota_password

# ================================================================================
#  Hardware
# ================================================================================

esphome:
  name: $sub_devicename
  platform: ESP32
  board: esp-wrover-kit
  build_path: builds/$sub_devicename/
  includes:
  - inkplate.h

  on_boot:
  - priority: 300
    then:
    - lambda: |-
        id(battery_voltage).update();
        id(should_deep_sleep).publish_state(!id(touch_3).state);

# deep_sleep:
#   sleep_duration: 5min
#   wakeup_pin_mode: INVERT_WAKEUP
#   esp32_ext1_wakeup:
#     pins: 34
#     mode: ALL_LOW

api:
  password: !secret ota_password
  id: hassio_api
  reboot_timeout: 0s
  services:
  - service: show_calendar
    then:
    - display.page.show: calendar
    - component.update: inkplate_display
  - service: add_event
    variables:
      title: string
      start_time: int
      end_time: int
      location: string
    then:
    - lambda: add_event(title, start_time, end_time, location);
  - service: events_added
    then:
    - component.update: battery_voltage
    - component.update: inkplate_display
    # - deep_sleep.enter:

globals:
- id: current_page
  type: int
  initial_value: "0"

switch:
- platform: restart
  name: "${sub_friendly_name} Reboot"
  id: reboot
- platform: gpio
  id: battery_read_mosfet
  name: "${sub_friendly_name} Battery Mosfet"
  pin:
    mcp23017: mcp23017_hub
    number: 9
    inverted: true

- platform: template
  name: "${sub_friendly_name} Greyscale"
  lambda: return id(inkplate_display).get_greyscale();
  turn_on_action:
  - lambda: id(inkplate_display).set_greyscale(true);
  turn_off_action:
  - lambda: id(inkplate_display).set_greyscale(false);

- platform: template
  name: "${sub_friendly_name} Partial Updating"
  lambda: return id(inkplate_display).get_partial_updating();
  turn_on_action:
  - lambda: id(inkplate_display).set_partial_updating(true);
  turn_off_action:
  - lambda: id(inkplate_display).set_partial_updating(false);

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: wifi_ip_address

sensor:
- platform: adc
  id: battery_voltage
  name: ${sub_friendly_name} Battery Voltage
  update_interval: never
  attenuation: 11db
  pin: 35
  filters:
  - calibrate_linear:
    - 2.10 -> 3.81
    - 2.20 -> 3.99
  on_value:
  - lambda: |-
      float state = 100 * (x - 3.3f) / (4.17f - 3.3f);
      state = clamp(state, 0, 100);
      id(battery_level).publish_state(state);
- platform: template
  id: battery_level
  name: ${sub_friendly_name} Battery Level
  accuracy_decimals: 0
  icon: mdi:battery
  update_interval: never

i2c:

mcp23017:
- id: mcp23017_hub
  address: 0x20

binary_sensor:
- platform: status
  name: "${sub_friendly_name} Node Status"
  id: system_status

- platform: template
  name: "${sub_friendly_name} Should Deep Sleep"
  id: should_deep_sleep

- platform: gpio
  name: "${sub_friendly_name} Touch Pad 1"
  id: touch_1
  pin:
    mcp23017: mcp23017_hub
    number: 10
    # interrupt: FALLING
- platform: gpio
  name: "${sub_friendly_name} Touch Pad 2"
  id: touch_2
  pin:
    mcp23017: mcp23017_hub
    number: 11
    # interrupt: FALLING
- platform: gpio
  name: "${sub_friendly_name} Touch Pad 3"
  id: touch_3
  pin:
    mcp23017: mcp23017_hub
    number: 12
    # interrupt: FALLING

time:
- platform: homeassistant
  id: esptime

# ================================================================================
#  Color Definitions
# ================================================================================

color:
- id: color_black
  red: 0%
  green: 0%
  blue: 0%
- id: color_gray
  red: 50%
  green: 50%
  blue: 50%

# ================================================================================
#  Typography
# ================================================================================

font:
  - file: "fonts/BDEject.ttf"
    id: fontPageTitle
    size: 20
    glyphs: "AGEND"
  - file: "fonts/04B_31__.ttf"
    id: fontPageSubTitle
    size: 12
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
  - file: "fonts/04B_31__.ttf"
    id: fontPageDay
    size: 12
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  - file: "fonts/digitalix.ttf"
    id: fontPageDate
    size: 19
    glyphs: "1234567890."
  - file: "fonts/Inter-Black.ttf"
    id: fontEventTitle
    size: 36
    glyphs: ${sub_glyphs}
  - file: "fonts/Inter-SemiBold.ttf"
    id: fontLocationString
    glyphs: ${sub_glyphs}
    size: 18
  - file: "fonts/visitor1.ttf"
    id: fontFooter1
    size: 19
    glyphs: ${sub_glyphs}
  - file: "fonts/Inter-SemiBold.ttf"
    id: font25
    size: 25
    glyphs: ${sub_glyphs}

display:
- platform: inkplate6
  id: inkplate_display
  partial_updating: false
  update_interval: never
  greyscale: true
  rotation: 270

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23017: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23017: mcp23017_hub
    number: 8
  oe_pin:
    mcp23017: mcp23017_hub
    number: 0
  spv_pin:
    mcp23017: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23017: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23017: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23017: mcp23017_hub
    number: 5

  pages:
  - id: calendar
    lambda: draw_agenda(it, id(color_gray));
